### ISSUE TITLE
CentOS 8.2 Issues

### ISSUE THREAD

**Issue by shapesandforms** [JustinTimperio/warp-cli#9]
Hi,

So the first two commands were successful but running the install script shows the following error.
Any idea what could be wrong?

[user@localhost ~]$ python3 /usr/app/warp-cli/core/warp.py --install
Warp-CLI is Now Setup and Registered in /usr/bin!
Do You Want to Attempt an Automatic WDT Build and Install? (y/n):y
Traceback (most recent call last):
  File "/usr/app/warp-cli/core/warp.py", line 148, in <module>
    setup_warp(base_dir)
  File "/usr/app/warp-cli/core/setup.py", line 55, in setup_warp
    build_wdt(base_dir)
  File "/usr/app/warp-cli/core/setup.py", line 29, in build_wdt
    sys.exit('Automated Package Installs for ' + os_name + ' Are NOT Supported.')
NameError: name 'sys' is not defined

Thank you

**Comment by JustinTimperio** [comment]
Hey @shapesandforms,

I'm actually in the process of reworking this entire repo because its a hot mess. Also, facebook has basically abandoned community support for WDT so I've had to change the build process to patch these issues. I'm hoping to finish up today or tomorrow.

**Comment by JustinTimperio** [comment]
Okay I just published a new release that fixes pretty much all the issues the last version had. 

I tested this on a CentOS 8 VM and in installed and ran fine. Try the new build process and let me know if it works for you.

**Comment by shapesandforms** [comment]
That was quick. Thank you, will test it right now.

**Comment by shapesandforms** [comment]
Thanks it looked like it worked. I ran into some issues with dependencies but I'm thinking I was missing "epel-release".

**Comment by JustinTimperio** [comment]
Yeah pretty sure you need epel-release and powertools for the dependencies.

That install script is safe for multiple runs so when your done, just run it.

If `warp - v` outputs version info on itself, wdt, and folly, your up and running.

**Comment by shapesandforms** [comment]
I'm running into some more issues. Maybe something I'm doing wrong. I have ssh access for my own user so no password neded and I created an alias called 'receiver' for the other box. 2x Centos 8.2 machines running on paralells, FW deactivated as well as selinux. I'm not running wdt manually on the second box. Is the ssh connection meant to start wdt on the receiving end?


`[user@sender ~]$ warp -p /tmp receiver /tmp
I0909 14:39:11.474750 11897 Throttler.cpp:58] wdt>	No average rate specified
I0909 14:39:11.474793 11897 Throttler.cpp:64] wdt>	No peak rate specified
I0909 14:39:11.474800 11897 WdtResourceController.cpp:29] wdt>	Updated max number of senders for _root controller_ to 0
I0909 14:39:11.474803 11897 WdtResourceController.cpp:22] wdt>	Updated max number of receivers for _root controller_ to 0
I0909 14:39:11.474808 11897 Wdt.cpp:24] wdt>	One time initialization of WDT for wdt
I0909 14:39:11.474815 11897 Throttler.cpp:81] wdt>	Updating the rates avgRatePerSec : -1048576.00 bucketRatePerSec : 0.00 tokenBucketLimit : 0.00
I0909 14:39:11.474828 11897 Receiver.cpp:44] wdt>	WDT Receiver 1.32.1910230 p 32
I0909 14:39:11.474844 11897 WdtBase.cpp:82] wdt>	Setting transfer id 1019878350
I0909 14:39:11.474849 11897 WdtBase.cpp:94] wdt>	using wdt protocol version 32
I0909 14:39:11.474858 11897 FileCreator.cpp:329] wdt>	dir already exists /
I0909 14:39:11.474864 11897 FileCreator.cpp:329] wdt>	dir already exists /tmp/
I0909 14:39:11.474869 11897 Receiver.cpp:172] wdt>	aes128gcm encryption is enabled for this transfer 
I0909 14:39:11.474871 11897 Receiver.cpp:175] wdt>	Receiver generating encryption key for type aes128gcm
I0909 14:39:11.474932 11897 EncryptionUtils.cpp:119] wdt>	New encryption params 0x7ffd6f98b200 2:...15374286878566359204...
I0909 14:39:11.475170 11897 ReceiverThread.cpp:1050] wdt>	Thread[0, port: 34611]  Listening on port 34611
I0909 14:39:11.475230 11897 ReceiverThread.cpp:1050] wdt>	Thread[1, port: 43683]  Listening on port 43683
I0909 14:39:11.475286 11897 ReceiverThread.cpp:1050] wdt>	Thread[2, port: 40463]  Listening on port 40463
I0909 14:39:11.475339 11897 ReceiverThread.cpp:1050] wdt>	Thread[3, port: 37223]  Listening on port 37223
I0909 14:39:11.475383 11897 ReceiverThread.cpp:1050] wdt>	Thread[4, port: 41625]  Listening on port 41625
I0909 14:39:11.475433 11897 ReceiverThread.cpp:1050] wdt>	Thread[5, port: 36771]  Listening on port 36771
I0909 14:39:11.475486 11897 ReceiverThread.cpp:1050] wdt>	Thread[6, port: 42571]  Listening on port 42571
I0909 14:39:11.475536 11897 ReceiverThread.cpp:1050] wdt>	Thread[7, port: 44779]  Listening on port 44779
I0909 14:39:11.475538 11897 Receiver.cpp:215] wdt>	Registered 8 successful sockets
I0909 14:39:11.475548 11897 wdtCmdLine.cpp:328] wdt>	Starting receiver with connection url wdt://receiver?Enc=2:...15374286878566359204...&dir=%2ftmp&id=1019878350&iv_change_int=34359738368&ports=34611,43683,40463,37223,41625,36771,42571,44779&recpv=32&tls=0
I0909 14:39:11.475592 11897 Receiver.cpp:458] wdt>	Starting (receiving) server on ports [ 34611 43683 40463 37223 41625 36771 42571 44779 ] Target dir : /tmp
I0909 14:39:11.475596 11897 Throttler.cpp:58] wdt>	No average rate specified
I0909 14:39:11.475597 11897 Throttler.cpp:64] wdt>	No peak rate specified
I0909 14:39:11.475600 11897 WdtBase.cpp:183] wdt>	Enabling throttling avgRate: -1048576.00, peakRate: 0.00, bucketLimit: 0.00, throttlerLogTimeMillis: 0
I0909 14:39:11.475862 11930 Receiver.cpp:399] wdt>	Progress reporter updating every 3000 ms
I0909 14:39:11.468572 11737 Throttler.cpp:58] wdt>	No average rate specified
I0909 14:39:11.468634 11737 Throttler.cpp:64] wdt>	No peak rate specified
I0909 14:39:11.468647 11737 WdtResourceController.cpp:29] wdt>	Updated max number of senders for _root controller_ to 0
I0909 14:39:11.468659 11737 WdtResourceController.cpp:22] wdt>	Updated max number of receivers for _root controller_ to 0
I0909 14:39:11.468667 11737 Wdt.cpp:24] wdt>	One time initialization of WDT for wdt
I0909 14:39:11.468678 11737 Throttler.cpp:81] wdt>	Updating the rates avgRatePerSec : -1048576.00 bucketRatePerSec : 0.00 tokenBucketLimit : 0.00
I0909 14:39:11.468722 11737 wdtCmdLine.cpp:288] wdt>	Parsed url as wdt://receiver?Enc=2:...15374286878566359204...&dir=%2ftmp&id=1019878350&iv_change_int=34359738368&ports=34611,43683,40463,37223,41625,36771,42571,44779&recpv=32&tls=0
I0909 14:39:11.468750 11737 wdtCmdLine.cpp:372] wdt>	Making Sender with encryption set = 1
I0909 14:39:11.468757 11737 WdtResourceController.cpp:373] wdt>	First time (default) is seen, creating.
I0909 14:39:11.468771 11737 WdtResourceController.cpp:29] wdt>	Updated max number of senders for  to 0
I0909 14:39:11.468775 11737 WdtResourceController.cpp:22] wdt>	Updated max number of receivers for  to 1
I0909 14:39:11.468782 11737 Throttler.cpp:81] wdt>	Updating the rates avgRatePerSec : -1048576.00 bucketRatePerSec : 0.00 tokenBucketLimit : 0.00
I0909 14:39:11.468801 11737 Sender.cpp:47] wdt>	WDT Sender 1.32.1910230 p 32
I0909 14:39:11.468820 11737 WdtResourceController.cpp:395] wdt>	Successfully added a sender for  identifier receiver
I0909 14:39:11.468827 11737 WdtBase.cpp:94] wdt>	using wdt protocol version 32
I0909 14:39:11.468837 11737 Sender.cpp:82] wdt>	Encryption is enabled for this transfer
I0909 14:39:11.468848 11737 DirectorySourceQueue.cpp:134] wdt>	Root dir now /tmp/
I0909 14:39:11.468861 11737 Sender.cpp:327] wdt>	Client (sending) to receiver, Using ports [ 34611 43683 40463 37223 41625 36771 42571 44779 ]
I0909 14:39:11.468873 11737 Sender.cpp:342] wdt>	Skipping throttler setup. External throttler set.Throttler details : avgRate: -1048576.00, peakRate: 0.00, bucketLimit: 0.00, throttlerLogTimeMillis: 0
I0909 14:39:11.469036 11739 DirectorySourceQueue.cpp:259] wdt>	Exploring root dir /tmp/ include_pattern :  exclude_pattern :  prune_dir_pattern : 
I0909 14:39:11.469060 11740 Sender.cpp:41] wdt>	Starting a new transfer 1019878350 to receiver
I0909 14:39:11.472074 11748 Sender.cpp:435] wdt>	Progress reporter tracking every 3000 ms
E0909 14:39:11.472169 11739 DirectorySourceQueue.cpp:284] wdt>	Error opening dir /tmp/systemd-private-c52967853f824099bfdc33b525a92add-chronyd.service-Bvvcse/: Permission denied [13]
E0909 14:39:11.472263 11739 DirectorySourceQueue.cpp:284] wdt>	Error opening dir /tmp/systemd-private-c52967853f824099bfdc33b525a92add-colord.service-wIigyX/: Permission denied [13]
E0909 14:39:11.472285 11739 DirectorySourceQueue.cpp:284] wdt>	Error opening dir /tmp/systemd-private-c52967853f824099bfdc33b525a92add-rtkit-daemon.service-zgehh1/: Permission denied [13]
E0909 14:39:11.472314 11739 DirectorySourceQueue.cpp:284] wdt>	Error opening dir /tmp/systemd-private-c52967853f824099bfdc33b525a92add-bolt.service-Kw5NbM/: Permission denied [13]
E0909 14:39:11.472342 11739 DirectorySourceQueue.cpp:284] wdt>	Error opening dir /tmp/systemd-private-c52967853f824099bfdc33b525a92add-fwupd.service-0CudLz/: Permission denied [13]
E0909 14:39:11.472388 11739 DirectorySourceQueue.cpp:284] wdt>	Error opening dir /tmp/systemd-private-c52967853f824099bfdc33b525a92add-ModemManager.service-tRYuRC/: Permission denied [13]
I0909 14:39:11.472425 11739 DirectorySourceQueue.cpp:408] wdt>	Number of files explored: 8 opened 0 with direct 0 errors true
E0909 14:39:11.553310 11747 ClientSocket.cpp:58] wdt>	Failed getaddrinfo receiver , 44779 : -2 : Name or service not known
E0909 14:39:11.553310 11740 ClientSocket.cpp:58] wdt>	Failed getaddrinfo receiver , 34611 : -2 : Name or service not known
I0909 14:39:11.553380 11747 SenderThread.cpp:988] wdt>	Thread[7, port: 44779]  Port 44779 done. Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = none. Total throughput = 0.00 Mbytes/sec
E0909 14:39:11.553325 11741 ClientSocket.cpp:58] wdt>	Failed getaddrinfo receiver , 43683 : -2 : Name or service not known
E0909 14:39:11.553335 11744 ClientSocket.cpp:58] wdt>	Failed getaddrinfo receiver , 41625 : -2 : Name or service not known
I0909 14:39:11.553393 11740 SenderThread.cpp:988] wdt>	Thread[0, port: 34611]  Port 34611 done. Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = none. Total throughput = 0.00 Mbytes/sec
I0909 14:39:11.553426 11744 SenderThread.cpp:988] wdt>	Thread[4, port: 41625]  Port 41625 done. Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = none. Total throughput = 0.00 Mbytes/sec
I0909 14:39:11.553413 11741 SenderThread.cpp:988] wdt>	Thread[1, port: 43683]  Port 43683 done. Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = none. Total throughput = 0.00 Mbytes/sec
E0909 14:39:11.561480 11743 ClientSocket.cpp:58] wdt>	Failed getaddrinfo receiver , 37223 : -2 : Name or service not known
E0909 14:39:11.561460 11745 ClientSocket.cpp:58] wdt>	Failed getaddrinfo receiver , 36771 : -2 : Name or service not known
E0909 14:39:11.561460 11742 ClientSocket.cpp:58] wdt>	Failed getaddrinfo receiver , 40463 : -2 : Name or service not known
E0909 14:39:11.561460 11746 ClientSocket.cpp:58] wdt>	Failed getaddrinfo receiver , 42571 : -2 : Name or service not known
I0909 14:39:11.561518 11743 SenderThread.cpp:988] wdt>	Thread[3, port: 37223]  Port 37223 done. Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = none. Total throughput = 0.00 Mbytes/sec
I0909 14:39:11.561553 11745 SenderThread.cpp:988] wdt>	Thread[5, port: 36771]  Port 36771 done. Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = none. Total throughput = 0.00 Mbytes/sec
I0909 14:39:11.561573 11742 SenderThread.cpp:988] wdt>	Thread[2, port: 40463]  Port 40463 done. Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = none. Total throughput = 0.00 Mbytes/sec
I0909 14:39:11.561591 11746 SenderThread.cpp:988] wdt>	Thread[6, port: 42571]  Port 42571 done. Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = none. Total throughput = 0.00 Mbytes/sec
I0909 14:39:11.561693 11746 Sender.cpp:28] wdt>	Last thread finished 0.09 for transfer id 1019878350
I0909 14:39:11.561873 11737 ThreadTransferHistory.cpp:106] wdt>	0 number of sources returned to queue, checkpoint: checkpoint-port: 0 num-blocks: 0 seq-id: 0 block-offset: 0 received-bytes: 0
I0909 14:39:11.561888 11737 ThreadTransferHistory.cpp:106] wdt>	0 number of sources returned to queue, checkpoint: checkpoint-port: 0 num-blocks: 0 seq-id: 0 block-offset: 0 received-bytes: 0
I0909 14:39:11.561892 11737 ThreadTransferHistory.cpp:106] wdt>	0 number of sources returned to queue, checkpoint: checkpoint-port: 0 num-blocks: 0 seq-id: 0 block-offset: 0 received-bytes: 0
I0909 14:39:11.561909 11737 ThreadTransferHistory.cpp:106] wdt>	0 number of sources returned to queue, checkpoint: checkpoint-port: 0 num-blocks: 0 seq-id: 0 block-offset: 0 received-bytes: 0
I0909 14:39:11.561915 11737 ThreadTransferHistory.cpp:106] wdt>	0 number of sources returned to queue, checkpoint: checkpoint-port: 0 num-blocks: 0 seq-id: 0 block-offset: 0 received-bytes: 0
I0909 14:39:11.561925 11737 ThreadTransferHistory.cpp:106] wdt>	0 number of sources returned to queue, checkpoint: checkpoint-port: 0 num-blocks: 0 seq-id: 0 block-offset: 0 received-bytes: 0
I0909 14:39:11.561934 11737 ThreadTransferHistory.cpp:106] wdt>	0 number of sources returned to queue, checkpoint: checkpoint-port: 0 num-blocks: 0 seq-id: 0 block-offset: 0 received-bytes: 0
I0909 14:39:11.561939 11737 ThreadTransferHistory.cpp:106] wdt>	0 number of sources returned to queue, checkpoint: checkpoint-port: 0 num-blocks: 0 seq-id: 0 block-offset: 0 received-bytes: 0
I0909 14:39:11.562108 11737 Reporting.cpp:130] wdt>	Error code summary CONN_ERROR
I0909 14:39:11.562120 11737 Reporting.cpp:146] wdt>	Could not send all the bytes 8231357146 0
[                                                 ]  0% 0.0 0.0 Mbytes/s  
I0909 14:39:11.562163 11737 Sender.cpp:253] wdt>	Total sender time = 0.09 seconds (0.00 dirTime). Transfer summary : Transfer status = BYTE_SOURCE_READ_ERROR. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = none. Previously sent bytes : 0. All files failed.
wdt>	Failed directories :
wdt>	/tmp/systemd-private-c52967853f824099bfdc33b525a92add-chronyd.service-Bvvcse/
wdt>	/tmp/systemd-private-c52967853f824099bfdc33b525a92add-colord.service-wIigyX/
wdt>	/tmp/systemd-private-c52967853f824099bfdc33b525a92add-rtkit-daemon.service-zgehh1/
wdt>	/tmp/systemd-private-c52967853f824099bfdc33b525a92add-bolt.service-Kw5NbM/
wdt>	/tmp/systemd-private-c52967853f824099bfdc33b525a92add-fwupd.service-0CudLz/
wdt>	/tmp/systemd-private-c52967853f824099bfdc33b525a92add-ModemManager.service-tRYuRC/
wdt>	
wdt>	Total sender throughput = 0.00 Mbytes/sec (0.00 Mbytes/sec pure transfer rate)
I0909 14:39:11.562196 11737 WdtResourceController.cpp:154] wdt>	Released the sender with id 1019878350
I0909 14:39:11.562199 11737 Wdt.cpp:132] wdt>	wdtSend for  receiver ended with BYTE_SOURCE_READ_ERROR
E0909 14:39:11.562296 11737 wdtCmdLine.cpp:381] wdt>	Returning with code 7 BYTE_SOURCE_READ_ERROR
I0909 14:39:11.562314 11737 WdtResourceController.cpp:310] wdt>	Shutting down the controller (0 senders 0 receivers)
E0909 14:40:01.760905 11927 ReceiverThread.cpp:155] wdt>	Thread[5, port: 36771]  Unable to accept after 500 attempts
I0909 14:40:01.760933 11927 ReceiverThread.cpp:911] wdt>	Thread[5, port: 36771]  entered FINISH_WITH_ERROR state
E0909 14:40:01.760913 11922 ReceiverThread.cpp:155] wdt>	Thread[0, port: 34611]  Unable to accept after 500 attempts
E0909 14:40:01.760932 11929 ReceiverThread.cpp:155] wdt>	Thread[7, port: 44779]  Unable to accept after 500 attempts
I0909 14:40:01.760960 11929 ReceiverThread.cpp:911] wdt>	Thread[7, port: 44779]  entered FINISH_WITH_ERROR state
E0909 14:40:01.760913 11928 ReceiverThread.cpp:155] wdt>	Thread[6, port: 42571]  Unable to accept after 500 attempts
I0909 14:40:01.760970 11927 Receiver.cpp:28] wdt>	Adding global checkpoint 36771 0 0
E0909 14:40:01.760972 11926 ReceiverThread.cpp:155] wdt>	Thread[4, port: 41625]  Unable to accept after 500 attempts
I0909 14:40:01.760974 11928 ReceiverThread.cpp:911] wdt>	Thread[6, port: 42571]  entered FINISH_WITH_ERROR state
I0909 14:40:01.760977 11926 ReceiverThread.cpp:911] wdt>	Thread[4, port: 41625]  entered FINISH_WITH_ERROR state
I0909 14:40:01.760987 11929 Receiver.cpp:28] wdt>	Adding global checkpoint 44779 0 0
I0909 14:40:01.760954 11922 ReceiverThread.cpp:911] wdt>	Thread[0, port: 34611]  entered FINISH_WITH_ERROR state
I0909 14:40:01.761014 11922 Receiver.cpp:28] wdt>	Adding global checkpoint 34611 0 0
I0909 14:40:01.760987 11927 ReceiverThread.cpp:1009] wdt>	Thread[5, port: 36771]  Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = aes128gcm.
I0909 14:40:01.761008 11929 ReceiverThread.cpp:1009] wdt>	Thread[7, port: 44779]  Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = aes128gcm.
I0909 14:40:01.761018 11922 ReceiverThread.cpp:1009] wdt>	Thread[0, port: 34611]  Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = aes128gcm.
E0909 14:40:01.761049 11923 ReceiverThread.cpp:155] wdt>	Thread[1, port: 43683]  Unable to accept after 500 attempts
I0909 14:40:01.761059 11923 ReceiverThread.cpp:911] wdt>	Thread[1, port: 43683]  entered FINISH_WITH_ERROR state
I0909 14:40:01.761066 11923 Receiver.cpp:28] wdt>	Adding global checkpoint 43683 0 0
I0909 14:40:01.761070 11923 ReceiverThread.cpp:1009] wdt>	Thread[1, port: 43683]  Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = aes128gcm.
E0909 14:40:01.761106 11925 ReceiverThread.cpp:155] wdt>	Thread[3, port: 37223]  Unable to accept after 500 attempts
I0909 14:40:01.761111 11925 ReceiverThread.cpp:911] wdt>	Thread[3, port: 37223]  entered FINISH_WITH_ERROR state
I0909 14:40:01.761118 11925 Receiver.cpp:28] wdt>	Adding global checkpoint 37223 0 0
I0909 14:40:01.761121 11925 ReceiverThread.cpp:1009] wdt>	Thread[3, port: 37223]  Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = aes128gcm.
I0909 14:40:01.761145 11928 Receiver.cpp:28] wdt>	Adding global checkpoint 42571 0 0
I0909 14:40:01.761159 11928 ReceiverThread.cpp:1009] wdt>	Thread[6, port: 42571]  Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = aes128gcm.
I0909 14:40:01.761178 11926 Receiver.cpp:28] wdt>	Adding global checkpoint 41625 0 0
I0909 14:40:01.761190 11926 ReceiverThread.cpp:1009] wdt>	Thread[4, port: 41625]  Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = aes128gcm.
E0909 14:40:01.761229 11924 ReceiverThread.cpp:155] wdt>	Thread[2, port: 40463]  Unable to accept after 500 attempts
I0909 14:40:01.761245 11924 ReceiverThread.cpp:911] wdt>	Thread[2, port: 40463]  entered FINISH_WITH_ERROR state
I0909 14:40:01.761255 11924 Receiver.cpp:28] wdt>	Adding global checkpoint 40463 0 0
W0909 14:40:01.761258 11924 Receiver.cpp:106] wdt>	WDT transfer did not start, no need to end session
I0909 14:40:01.761260 11924 ReceiverThread.cpp:1009] wdt>	Thread[2, port: 40463]  Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = aes128gcm.
E0909 14:40:01.761410 11897 Reporting.cpp:204] wdt>	Did not receive all the blocks sent by the sender -1 0
W0909 14:40:01.761427 11897 Receiver.cpp:334] wdt>	WDT receiver's transfer has been finished
I0909 14:40:01.761430 11897 Receiver.cpp:335] wdt>	Transfer status (local) = CONN_ERROR, (remote) = OK. Number of blocks transferred = 0. Data Mbytes = 0.00. Header Kbytes = 0.00 (100.00% overhead). Total bytes = 0. Wasted bytes due to failure = 0 (100.00% overhead). Encryption type = none. Previously sent bytes : 0.
W0909 14:40:01.761462 11897 Receiver.cpp:303] wdt>	Threads have already been joined. Returning the transfer report
E0909 14:40:01.761466 11897 Reporting.cpp:204] wdt>	Did not receive all the blocks sent by the sender -1 0
E0909 14:40:01.761560 11897 wdtCmdLine.cpp:381] wdt>	Returning with code 3 CONN_ERROR
I0909 14:40:01.761600 11897 WdtResourceController.cpp:310] wdt>	Shutting down the controller (0 senders 0 receivers)
`

**Comment by JustinTimperio** [comment]
Well from the log it looks like your try to transplant an entire /tmp dir from one machine to another which is super bad idea. Wdt would need the permissions to basically delete the target machines /tmp(thus this being a terrible idea) The error you are getting is about target directories permissions if you read through it. 

Also for some reason, wdt is just bork on my network so I need to overwrite the host name with my receiver machines local ipv4 address. I added a flag to handle this so just call `-fh` if you still have issues after trying another directory.

**Comment by shapesandforms** [comment]
Ah yeah it was a "dns" issue. Once I added "receiver" to my hosts file the transfer started. I was sure I already did that but that was likely on a previous test. Also good to know about the directories. Much appreciated.
